spring:
  datasource:
    password: root-bobao
    username: fornecedor
    url: jdbc:mysql://localhost:3306/fornecedor?useTimezone=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
